es_test/config/routes.rb
EsTest::Application.routes.draw do
  resources :articles

end

es_test/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :text, :title
end

es_test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

es_test/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    #@article = Article.new(article_params)
    @article = Article.new(params[:article])
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)      
    end
end

es_test/app/helpers/application_helper.rb
module ApplicationHelper
end

es_test/app/helpers/articles_helper.rb
module ArticlesHelper
end

es_test/app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<ul>
  <% @articles.each do |article| %>
    <li>
      <h3><%= article.title %></h3>
      <p><%= article.text %></p>
    </li>
  <% end %>
</ul>
<%= link_to 'New Article', new_article_path %>

es_test/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>
  <% if not @article.nil? && @article.errors.any? %>
    <div id="error_explaination">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved.</h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %> <br />
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to '<- Back', articles_path %>

es_test/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to '<- Back', articles_path %>

es_test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EsTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>